### ISSUE TITLE
Bit Rates output in MLP file 

### ISSUE THREAD

**Issue by kalra333** [scelesticsiva/Neural-Networks-for-Image-Compression#2]
I have a strange doubt . I run the image(already present ) compression using MLP file. Bit rates obtained are 115.69728469848633 bpp for original image ,  63.74600018896745 bpp with linear regression but can't we   represent any pixel vale in 32 bit(upto 10^9)  . I am treating pixel values as integers. How the value of bpp is so high?

**Comment by ozantezcan** [comment]
Hi kaira333,

I am not sure I understand how did you get 115.xx bpp and 63.xx bpps. Did you run the code successfully using the example image?  (lena512.bmp) It is a grayscale image which uses 8 bits to represent a single pixel value. So, the original image is 8 bpp without any coding algorithm. When you run the 3rd block, it will do the Huffman coding to the original pixel values and calculate the new bpp. When I run this block, I get ~7.468 bpp. 

If you are getting ~115.697 bpp on the example image, there might be a version difference in one of the libraries. For a quick check, can you sent me the lengths of 'huffman_img[1]' and 'img_input' after you run the 3rd code block?

**Comment by kalra333** [comment]
lenghth of huffman_img[1] - 30329349
length of img_input -  262144

**Comment by ozantezcan** [comment]
It's weird. I don't have a guess about the reason for now. I will try to solve it and reply again if I will have a solution.

**Comment by kalra333** [comment]
I made some error in compare function. I got it now .Thanks for your help and time.
